_wandb:
    value:
        cli_version: 0.23.1
        e:
            bhyv1xra43o7sl8wvp3yddwwzn2zc70z:
                codePath: c:\Users\meekg\Downloads\sep-25-dl-gen-ai-nppe-2\notesree_enhanced.ipynb
                codePathLocal: notesree_enhanced.ipynb
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "11.5"
                disk:
                    /:
                        total: "489172234240"
                        used: "430589661184"
                email: 23f2002825@ds.study.iitm.ac.in
                executable: c:\Users\meekg\AppData\Local\Programs\Python\Python312\python.exe
                gpu: NVIDIA GeForce RTX 3060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      name: NVIDIA GeForce RTX 3060 Laptop GPU
                      uuid: GPU-cf51ffcc-c59a-2625-f773-105b005f00a9
                host: MSI
                memory:
                    total: "16992980992"
                os: Windows-11-10.0.26200-SP0
                program: c:\Users\meekg\Downloads\sep-25-dl-gen-ai-nppe-2\notesree_enhanced.ipynb
                python: CPython 3.12.0
                root: c:\Users\meekg\Downloads\sep-25-dl-gen-ai-nppe-2
                startedAt: "2025-12-15T19:15:17.673003Z"
                writerId: bhyv1xra43o7sl8wvp3yddwwzn2zc70z
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 1
                - 5
                - 53
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 105
            "3":
                - 1
                - 2
                - 3
                - 13
                - 16
            "4": 3.12.0
            "5": 0.23.1
            "8":
                - 1
                - 2
                - 3
            "10":
                - 21
            "12": 0.23.1
            "13": windows-amd64
batch_size:
    value: 32
c3_classes:
    value: 3
c8_classes:
    value: 8
device:
    value: cuda
embed_dim:
    value: 64
epochs:
    value: 10
hidden_dim:
    value: 128
learning_rate:
    value: 0.001
max_len:
    value: 1632
vocab_size:
    value: 22
